### ISSUE TITLE
Feedback Técnico

### ISSUE THREAD

**Issue by RuthSalvador** [andrealemonroy/lim-2018-05-bc-core-am-socialnetwork#20]
# Recomendaciones de mejora 

**Todas las integrantes deberían tener la misma información y cada una tiene una versión diferente, se corrige al azar**

### Estructura de carpetas:
Utiliza carpetas para organizar tus archivos; en el caso de imágenes, puedes tenerlas todas en una carpeta o subirlas en la nube y luego linkearlas; en el caso de js puedes organizarlo por funcionalidades, hay un archivo `all.js` que está afuera de la carpeta `js`.

### package.json:
Recuerda que debes utilizar `eslint`, el cual se encarga de revisar tu código y te indica los errores de estilo que podrías corregir para mejorar tu proyecto; en este caso no tienes esta dependencia descargada. Hay diferentes configuraciones de este archivo en las integrantes.

### Git:
Es recomendable que "comitées" por funcionalidades y no en bloque, a la vez estos commits deben ser descriptivos, evita usar: final prueba, final prueba dos, editar prueba (5 veces), etc. Recuerda verificar el nombre de los `pull requests` ya que éstos se ven reflejados como commits, por lo que deben ser descriptivos.

### Github:
Es necesario que tu siguiente proyecto tenga como mínimo los niveles solicitados, está faltando `releases`; con respecto a los `issues` y `milestones` deberían cerrarse cuando se completen y no de forma "ficticia" (fueron cerrados el 09 agosto, sin embargo presentaste el proyecto semanas atrás)

### Javascript:
- Se considera una buena práctica utilizar los operadores de igualdad de tipo seguro `===` y `!==` en lugar de sus contrapartes regulares `==` y `!=`.
- Hay funciones y variables que declaras y no utilizas: removeLikeFromPost.
- Es mejor usar el `evento click` en lugar del `atributo onClick`.
- Usen `ES6` en lugar de `js5` hay varias variables definidas con `var`.
- Puedes optar por agregar algunos datos del usuario, como nombre para saber de quienes son los posts.

### Tests:
Para ver la cobertura de tus tests, una forma es instalando la dependencia `nyc`. Estás pasando la cobertura solicitada, puedes testear más partes de tu código como el muro.

### index.html:
Recuerda que debes validar tu `html`, te recomendamos revisar el [enlace](https://validator.w3.org/nu/?doc=https%3A%2F%2Fdcrisanto.github.io%2Flim-2018-05-bc-core-am-socialnetwork%2Fsrc%2F) para mayor especificación, también valida los otros `html`que tienes. Te sugerimos utilizar más etiquetas semánticas, así como sus propiedades. Cuida tu indentación. 

### style.css:
Mejora el responsive. Utiliza más clases, ten cuidado al indicar estilos, estás repitiendo.
https://github.com/dcrisanto/lim-2018-05-bc-core-am-socialnetwork/blob/00e90173d7be1339409978b3eda76e1c19bd6746/src/style.css#L51-L58

Por último te recomendamos utilizar convenciones para tus archivos, de tal forma que se mantenga un orden y se vea profesional.
Recuerda declarar tus variables, clases, id con nombres en inglés y descriptivas.
**Actualizan sus repositorios, al ser un trabajo grupal todas deben tener el mismo contenido**

Espero puedas implementar este feedback en tus proyectos.

**Comment by andrealemonroy** [comment]
Ok. Gracias!
